### ISSUE TITLE
model-full.py has array reshaping errors .

### ISSUE THREAD

**Issue by codepujan** [0bserver07/Keras-SegNet-Basic#3]
Hello .the Normal  Model compiles well but the model_full.py has error  on the lower part : because of the reshaping problem . Line 140
`segnet_basic.add(Reshape((n_labels, img_h * img_w), input_shape=(12,img_h, img_w)))
`

They seem to be  fine mathematically too . The simplemodel definition(model-basic.py )  is similar like this yet it works .But teh Model-full.py has error in this part . 

Any help diagnosing this would be great .

**Comment by 0bserver07** [comment]
Perhaps update to the latest version, and make sure to set the model to use 'th' for theano, or just change the order to be used for TF
