### ISSUE TITLE
SegNet_Basic.py

### ISSUE THREAD

**Issue by mohanrajmit** [0bserver07/Keras-SegNet-Basic#5]
Hi,

I have few clarifications in SegNet_Basic.py  at line 28.

class_weighting= [0.2595, 0.1826, 4.5640, 0.1417, 0.5051, 0.3826, 9.6446, 1.8418, 6.6823, 6.2478, 3.0, 7.3614]

I would like to know how this values are assigned to class weighting.

Regards
Mohan

**Comment by 0bserver07** [comment]
The equation is from this paper:

[Predicting Depth, Surface Normals and Semantic Labels
with a Common Multi-Scale Convolutional Architecture](https://arxiv.org/pdf/1411.4734v4.pdf)

I got it from the original paper: Check out this issue on the Caffe implementation:

https://github.com/alexgkendall/SegNet-Tutorial/issues/31

`
we weight each pixel by αc = median freq/freq(c)  where freq(c) is the number of pixels of class c divided by the total  number of pixels in images where c is present, and median freq is the  median # of these frequencies. _
`

**Comment by mohanrajmit** [comment]
thanks for your reply. The above information cleared my doubt.

**Comment by 0bserver07** [comment]
coo beans, i will close the ticket
